apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
  namespace: qa
  labels:
    app: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  replicas: 1
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
