name: Docker Image angular

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]
    
env:
  PATH_DOCKERFILE: front
jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depht: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Download dependencies with NPM
        run: npm ci
        working-directory: front
      
      - name: test CI with NPM
        run: npm run test-ci
        working-directory: front
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:v1
        working-directory: ${{ env.PATH_DOCKERFILE}}
      - name: acr-sign-push
  # You may pin to the exact commit or the version.
  # uses: dodopizza/acr-sign-push-action@6688de830a974866ae37da84ecf180b5aed8ebaf
        uses: dodopizza/acr-sign-push-action@0.1.2
        with:
          # image tags separated by comma, example: example.azurecr.io/app:latest
          tags: my-image-name:v1
            # signer key id (hash)
          signer-key-id: TokenGitHub
            # signer key content base64 encoded
          signer-key: di+MTnmUUEoqe9GcnojItwgpmZUgn4917bWAiQ1Ze85+ACRA5Ctvk
            # repository passphrase
          repository-passphrase: devsecopscelula.azurecr.io
